# Generated by Django 4.1 on 2022-08-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("si", models.CharField(default="", max_length=10)),
                ("gu", models.CharField(default="", max_length=10)),
                ("dong", models.CharField(default="", max_length=10)),
                ("detail_loc", models.TextField()),
                ("latitude", models.TextField()),
                ("longitude", models.TextField()),
            ],
        ),
    ]
