# Generated by Django 4.0.5 on 2022-08-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
