# Generated by Django 4.1 on 2022-08-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("irion", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="LocationSnippet", new_name="Location",),
        migrations.AlterModelOptions(name="location", options={},),
    ]
